//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artikli_na_skladistu
    {
        public int id_artikli_na_skladistu { get; set; }
        public int kolicina { get; set; }
        public int skladiste { get; set; }
        public int artikl { get; set; }
    
        public virtual Artikl Artikl1 { get; set; }
        public virtual Skladiste Skladiste1 { get; set; }
    }
}
