//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dnevnik_rada
    {
        public int id_dnevnik_rada_zaposlenika { get; set; }
        public System.DateTime datum_obavljanja_rada { get; set; }
        public string opis_rada { get; set; }
        public int korisnik { get; set; }
        public int radnja_dnevnika { get; set; }
    
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Radnja_dnevnika Radnja_dnevnika1 { get; set; }
    }
}
