//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokument()
        {
            this.Stavke_dokumenta = new HashSet<Stavke_dokumenta>();
        }
    
        public int id_dokument { get; set; }
        public System.DateTime datum_izdavanja { get; set; }
        public string opis_dokumenta { get; set; }
        public Nullable<double> ukupni_saldo { get; set; }
        public int tip_dokumenta { get; set; }
        public Nullable<int> korisnik { get; set; }
        public int zaposlenik { get; set; }
    
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Korisnik Korisnik2 { get; set; }
        public virtual Tip_dokumenta Tip_dokumenta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke_dokumenta> Stavke_dokumenta { get; set; }
    }
}
