//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Korisnik()
        {
            this.Dnevnik_rada = new HashSet<Dnevnik_rada>();
            this.Dokuments = new HashSet<Dokument>();
            this.Dokuments1 = new HashSet<Dokument>();
            this.Obavijests = new HashSet<Obavijest>();
            this.Obavijests1 = new HashSet<Obavijest>();
        }
    
        public int id_korisnik { get; set; }
        public string ime_korisnika { get; set; }
        public string prezime_korisnika { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string IBAN { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public int tip_korisnika { get; set; }
        public Nullable<int> poslovnica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dnevnik_rada> Dnevnik_rada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dokument> Dokuments1 { get; set; }
        public virtual Poslovnica Poslovnica1 { get; set; }
        public virtual Tip_korisnika Tip_korisnika1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavijest> Obavijests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavijest> Obavijests1 { get; set; }
    }
}
