//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavijest
    {
        public int Id { get; set; }
        public string Naslov { get; set; }
        public string Opis { get; set; }
        public int Zaposlenik { get; set; }
        public int Korisnik { get; set; }
        public byte Procitano { get; set; }
        public System.DateTime Vrijeme_kreiranja { get; set; }
    
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual Korisnik Korisnik2 { get; set; }
    }
}
