//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladiste_poslovnice
    {
        public int id_skladiste_poslovnice { get; set; }
        public int poslovnica { get; set; }
        public int skladiste { get; set; }
    
        public virtual Poslovnica Poslovnica1 { get; set; }
        public virtual Skladiste Skladiste1 { get; set; }
    }
}
