//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sloj_pristupa_podacima
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stavke_dokumenta
    {
        public int id_stavke_dokumenta { get; set; }
        public int artikl { get; set; }
        public int dokument { get; set; }
        public int usluga { get; set; }
    
        public virtual Artikl Artikl1 { get; set; }
        public virtual Dokument Dokument1 { get; set; }
        public virtual Usluga Usluga1 { get; set; }
    }
}
